### ISSUE TITLE
If entities renamed the switches won't report the state 

### ISSUE THREAD

**Issue by ShayGus** [0xAlon/dolphin#4]
When switches renamed, 
they will become unavailable when showers enabled from app.
 Example:
 I renamed the switches to switch.dolphin_1_showers - switch.dolphin_4_showers (I have 150L boiler)
 If I trigger the number of showers from HA it appears as on
 If I trigger the number of showers from the app all switches become unavailable.

**Edit
Not sure if this behavior is related to changing the id.
It seems to me that when turning on dolphin from the app the drop switches become unavailable, even if in the app it turned on.
It seems to  me that these drop switches either need to be compared to current temp. and turn on in case the temp is equal or they should be exposed as services.

**Comment by 0xAlon** [comment]
Hi @ShayGus,

The switches are currently under development.
As soon as the boiler is on, the switches become unavailable. When the boiler is off, the switches are available. For now, when using the switches the data will be updated in the thermostat entity but will change all the switches states to unavailable. The switches state return to available when the boiler reaches the  temperature and will turn off.

**Comment by ShayGus** [comment]
Are you developing the official to be integration or is this a private initiative?

**Comment by 0xAlon** [comment]
This project was developed in collaboration with dolphin
